Repository ToucanToco/toucan-connectors, pull requests merged in 2018-09, with the labels that each got.

#27 Feature :: hive connector
  doc/connectors.md
  doc/hive.md
  setup.py
  tests/conftest.py
  tests/docker-compose.yml
  tests/hive/test_hive.py
  toucan_connectors/__init__.py
  toucan_connectors/hive/__init__.py
  toucan_connectors/hive/hive_connector.py
Labels: enhancement, wip

#29 Hotfix :: Add google credentials to Google Analytics doc
  doc/google_analytics.md
Labels: doc

#32 Feature :: decode bytes columns for MySQL
  setup.py
  tests/mysql/test_mysql.py
  toucan_connectors/mysql/mysql_connector.py
Labels: Need Review, enhancement

#30 Hotfix :: Update oracle_sql installation doc
  doc/oracle_sql.md
Labels: doc

#34 features :: HttpAPI connector
  doc/connectors.md
  doc/http_api.md
  setup.py
  tests/http_api/test_http_api.py
  toucan_connectors/__init__.py
  toucan_connectors/http_api/__init__.py
  toucan_connectors/http_api/http_api_connector.py
Labels: Need Review, enhancement
