Repository ToucanToco/toucan-connectors, pull requests merged in 2018-11, with the labels that each got.

#51 Magento :: add connector
  doc/connectors.md
  doc/magento.md
  setup.py
  tests/magento/test_magento.py
  toucan_connectors/__init__.py
  toucan_connectors/magento/__init__.py
  toucan_connectors/magento/magento_connector.py
Labels: enhancement

#57 Hotfix :: Right dependencies for Google connectors
  setup.py
Labels: Need Review, bug

#56 OData :: improvements (better names for params, more auth)
  doc/http_api.md
  doc/odata.md
  setup.py
  tests/odata/test_odata.py
  tests/test_common.py
  toucan_connectors/common.py
  toucan_connectors/odata/odata_connector.py
Labels: wip
