Repository ToucanToco/toucan-connectors, pull requests merged in 2018-10, with the labels that each got.

#38 Hotfix :: mongo with divide
  setup.py
  tests/mongo/test_mongo.py
  toucan_connectors/mongo/mongo_connector.py
Labels: Need Review, bug

#41 Feature :: Google Big Query connector
  doc/adobe_analytics.md
  doc/azure_mssql.md
  doc/connectors.md
  doc/dataiku.md
  doc/generate.py
  doc/google_analytics.md
  doc/google_big_query.md
  doc/google_cloud_mysql.md
  doc/google_credentials.md
  doc/google_spreadsheet.md
  doc/hive.md
  doc/http_api.md
  doc/micro_strategy.md
  doc/mongo.md
  doc/mssql.md
  doc/mysql.md
  doc/oracle_sql.md
  doc/postgres.md
  doc/sap_hana.md
  doc/snowflake.md
  doc/toucan_toco.md
  setup.py
  tests/google_big_query/test_google_big_query.py
  toucan_connectors/__init__.py
  toucan_connectors/google_big_query/__init__.py
  toucan_connectors/google_big_query/google_big_query_connector.py
Labels: Need Review, enhancement

#42 Feature :: add skip_rows for google spreadsheet
  doc/google_spreadsheet.md
  setup.py
  toucan_connectors/google_spreadsheet/google_spreadsheet_connector.py
Labels: Need Review, enhancement

#44 Feature :: Google Analytics segmentId
  setup.py
  toucan_connectors/google_analytics/google_analytics_connector.py
Labels: enhancement

#43 http api connector :: Add support for oauth2 "backend application flow"
  doc/http_api.md
  setup.py
  tests/http_api/test_http_api.py
  toucan_connectors/http_api/http_api_connector.py
Labels: enhancement
