Repository ToucanToco/toucan-connectors, pull requests merged in 2019-06, with the labels that each got.

#81 Feature :: add methods get_df_and_count + explain
  setup.py
  tests/mongo/test_mongo.py
  tests/test_connector.py
  toucan_connectors/mongo/mongo_connector.py
  toucan_connectors/toucan_connector.py
Labels: Need Review, enhancement

#80 Implement a retry policy on connectors.
  setup.py
  tests/test_connector.py
  tests/test_retry_policy.py
  toucan_connectors/toucan_connector.py
Labels: enhancement

#82 Get status and all connectors
  README.md
  templates/connector.py.m4
  tests/mongo/test_mongo.py
  tests/mysql/test_mysql.py
  tests/test_connector.py
  toucan_connectors/__init__.py
  toucan_connectors/adobe_analytics/adobe_analytics_connector.py
  toucan_connectors/azure_mssql/azure_mssql_connector.py
  toucan_connectors/dataiku/dataiku_connector.py
  toucan_connectors/elasticsearch/elasticsearch_connector.py
  toucan_connectors/facebook_insights/facebook_insights_connector.py
  toucan_connectors/google_analytics/google_analytics_connector.py
  toucan_connectors/google_big_query/google_big_query_connector.py
  toucan_connectors/google_cloud_mysql/google_cloud_mysql_connector.py
  toucan_connectors/google_my_business/google_my_business_connector.py
  toucan_connectors/google_spreadsheet/google_spreadsheet_connector.py
  toucan_connectors/hive/hive_connector.py
  toucan_connectors/http_api/http_api_connector.py
  toucan_connectors/micro_strategy/micro_strategy_connector.py
  toucan_connectors/mongo/mongo_connector.py
  toucan_connectors/mssql/mssql_connector.py
  toucan_connectors/mysql/mysql_connector.py
  toucan_connectors/odata/odata_connector.py
  toucan_connectors/oracle_sql/oracle_sql_connector.py
  toucan_connectors/postgres/postgresql_connector.py
  toucan_connectors/sap_hana/sap_hana_connector.py
  toucan_connectors/snowflake/snowflake_connector.py
  toucan_connectors/toucan_connector.py
  toucan_connectors/toucan_toco/toucan_toco_connector.py
  toucan_connectors/trello/trello_connector.py
Labels: Need Review, enhancement

#84 Hotfix :: OData connector
  setup.py
  tests/odata/test_odata.py
  toucan_connectors/odata/odata_connector.py
Labels: bug
