Repository ToucanToco/toucan-connectors, pull requests merged in 2019-11, with the labels that each got.

#121 Snowflake :: fix with use warehouse
  tests/snowflake/test_snowflake.py
  toucan_connectors/snowflake/snowflake_connector.py
Labels: Need Review, TO MERGE

#123 Add shell install scripts for some connectors
  .circleci/config.yml
  setup.py
  toucan_connectors/install_scripts/__init__.py
  toucan_connectors/install_scripts/azure_mssql.sh
  toucan_connectors/install_scripts/databricks.sh
  toucan_connectors/install_scripts/oracle.sh
Labels: tech

#124 MANIFEST.IN :: add missing bash scripts
  setup.py
Labels: bug
