Repository ToucanToco/toucan-connectors, pull requests merged in 2019-07, with the labels that each got.

#86 microstrat :: improvements
  doc/connectors/micro_strategy.md
  setup.py
  tests/micro_strategy/fixtures/fixture_search.json
  tests/micro_strategy/test_microstrategy.py
  toucan_connectors/micro_strategy/client.py
  toucan_connectors/micro_strategy/data.py
  toucan_connectors/micro_strategy/micro_strategy_connector.py
Labels: Need Review, enhancement

#89 [template] follow recent get_df vs. _retrieve_data API changes
  README.md
  templates/connector.py.m4
Labels: Need Review, doc

#90 Tech :: Make jq required
  setup.py
Labels: Need Review, tech

#88 wootric :: new connector
  doc/connectors.md
  doc/connectors/wootric.md
  requirements-testing.txt
  setup.py
  tests/wootric/test_wootric.py
  toucan_connectors/__init__.py
  toucan_connectors/wootric/__init__.py
  toucan_connectors/wootric/wootric_connector.py
Labels: TO MERGE, enhancement

#91 Fix :: Fix requirements by connector
  requirements-testing.txt
  setup.py
  tests/google_big_query/test_google_big_query.py
  tests/test_common.py
  toucan_connectors/auth.py
  toucan_connectors/common.py
  toucan_connectors/google_analytics/google_analytics_connector.py
  toucan_connectors/google_big_query/google_big_query_connector.py
  toucan_connectors/google_credentials.py
  toucan_connectors/google_spreadsheet/google_spreadsheet_connector.py
  toucan_connectors/http_api/http_api_connector.py
  toucan_connectors/odata/odata_connector.py
Labels: bug, tech

#95 mongo connector :: fix get_df_and_count when the query uses $group aggregation
  setup.py
  tests/mongo/test_mongo.py
  toucan_connectors/mongo/mongo_connector.py
Labels: Need Review, bug

#93 Feature :: Add jinja to render parameters in query and permissions
  setup.py
  tests/mongo/test_mongo.py
  tests/test_auth.py
  tests/test_common.py
  tests/test_connector.py
  toucan_connectors/common.py
  toucan_connectors/elasticsearch/elasticsearch_connector.py
  toucan_connectors/google_analytics/google_analytics_connector.py
  toucan_connectors/hive/hive_connector.py
  toucan_connectors/http_api/http_api_connector.py
  toucan_connectors/micro_strategy/micro_strategy_connector.py
  toucan_connectors/mongo/mongo_connector.py
  toucan_connectors/mysql/mysql_connector.py
  toucan_connectors/postgres/postgresql_connector.py
  toucan_connectors/toucan_connector.py
Labels: enhancement

#94 Elasticsearch :: Read aggregations in response
  tests/elasticsearch/test_elasticsearch.py
  toucan_connectors/elasticsearch/elasticsearch_connector.py
Labels: TO MERGE, enhancement

#97 Mongo :: translate jinja + fix $sort
  setup.py
  tests/mongo/test_mongo.py
  tests/mongo/test_mongo_translator.py
  toucan_connectors/common.py
  toucan_connectors/mongo/mongo_connector.py
  toucan_connectors/mongo/mongo_translator.py
Labels: Need Review, enhancement

#98 microstrat connector :: add ability to target an attribute or a metric using its raw ID
  setup.py
  tests/micro_strategy/test_microstrategy.py
  toucan_connectors/micro_strategy/data.py
Labels: Need Review, enhancement

#96 Feature :: get form
  doc/connectors/azure_mssql.md
  doc/connectors/google_cloud_mysql.md
  doc/connectors/hive.md
  doc/connectors/mongo.md
  doc/connectors/mssql.md
  doc/connectors/mysql.md
  doc/connectors/postgres.md
  doc/generate.py
  setup.py
  tests/azure_mssql/test_azure_mssql.py
  tests/google_cloud_mysql/test_google_cloud_mysql.py
  tests/mongo/test_mongo.py
  tests/mssql/test_mssql.py
  tests/mysql/test_mysql.py
  tests/postgres/test_postgres.py
  tests/test_connector.py
  tests/test_datasource.py
  toucan_connectors/__init__.py
  toucan_connectors/azure_mssql/azure_mssql_connector.py
  toucan_connectors/google_cloud_mysql/google_cloud_mysql_connector.py
  toucan_connectors/hive/hive_connector.py
  toucan_connectors/mongo/mongo_connector.py
  toucan_connectors/mssql/mssql_connector.py
  toucan_connectors/mysql/mysql_connector.py
  toucan_connectors/oracle_sql/oracle_sql_connector.py
  toucan_connectors/postgres/postgresql_connector.py
  toucan_connectors/snowflake/snowflake_connector.py
  toucan_connectors/toucan_connector.py
Labels: enhancement

#100 Fix :: handle dot syntax for dict in jinja templates
  setup.py
  tests/test_common.py
  toucan_connectors/common.py
Labels: bug
