Repository ToucanToco/toucan-connectors, pull requests merged in 2019-09, with the labels that each got.

#108 Fix :: pagination of get_slice connectors method
  tests/test_connector.py
  toucan_connectors/toucan_connector.py
Labels: bug

#111 Fix :: get_slice with no limit
  tests/test_connector.py
  toucan_connectors/toucan_connector.py
Labels: Need Review, bug

#112 README :: Add a step for `make format`
  README.md
Labels: doc
