Repository ToucanToco/toucan-connectors, pull requests merged in 2019-04, with the labels that each got.

#68 Upgrade pydantic
  .circleci/config.yml
  README.md
  setup.py
  tests/http_api/test_http_api.py
  tests/mongo/test_mongo.py
  tests/mssql/test_mssql.py
  tests/mysql/test_mysql.py
  tests/postgres/test_postgres.py
  tests/sap_hana/test_sap_hana.py
  tests/test_datasource.py
  toucan_connectors/google_analytics/google_analytics_connector.py
  toucan_connectors/http_api/http_api_connector.py
  toucan_connectors/toucan_connector.py
Labels: tech

#70 GoogleMyBusiness connector
  doc/google_my_business.md
  doc/img/google_credentials_screenshot.jpg
  setup.py
  tests/google_my_business/test_google_my_business.py
  toucan_connectors/common.py
  toucan_connectors/google_my_business/__init__.py
  toucan_connectors/google_my_business/google_my_business_connector.py
Labels: enhancement

#75 Feature :: add connector elasticsearch
  doc/connectors.md
  doc/elasticsearch.md
  doc/magento.md
  setup.py
  tests/docker-compose.yml
  tests/elasticsearch/test_elasticsearch.py
  toucan_connectors/__init__.py
  toucan_connectors/elasticsearch/__init__.py
  toucan_connectors/elasticsearch/elasticsearch_connector.py
Labels: enhancement

#77 Feature :: move doc to simplify auto generation in docs.toucantoco.com
  doc/connectors.md
  doc/connectors/adobe_analytics.md
  doc/connectors/azure_mssql.md
  doc/connectors/dataiku.md
  doc/connectors/elasticsearch.md
  doc/connectors/facebook_insights.md
  doc/connectors/google_analytics.md
  doc/connectors/google_big_query.md
  doc/connectors/google_cloud_mysql.md
  doc/connectors/google_my_business.md
  doc/connectors/google_spreadsheet.md
  doc/connectors/hive.md
  doc/connectors/http_api.md
  doc/connectors/micro_strategy.md
  doc/connectors/mongo.md
  doc/connectors/mssql.md
  doc/connectors/mysql.md
  doc/connectors/odata.md
  doc/connectors/oracle_sql.md
  doc/connectors/postgres.md
  doc/connectors/sap_hana.md
  doc/connectors/snowflake.md
  doc/connectors/toucan_toco.md
  doc/generate.py
  doc/google_credentials.md
  doc/google_spreadsheet.md
  doc/img/google_credentials_screenshot.jpg
Labels: doc
