Repository ToucanToco/toucan-connectors, pull requests merged in 2020-08, with the labels that each got.

#188 fix(mongo): fix status error format
  tests/mongo/test_mongo.py
Labels: bug

#186 BigQuery :: fix scopes label
  toucan_connectors/google_big_query/google_big_query_connector.py
Labels: bug

#185 feat: creates Revinate connector module
  doc/connectors/revinate.md
  tests/revinate/test_revinate.py
  tests/revinate/test_revinate_helpers.py
  toucan_connectors/__init__.py
  toucan_connectors/revinate/__init__.py
  toucan_connectors/revinate/helpers.py
  toucan_connectors/revinate/revinate.png
  toucan_connectors/revinate/revinate_connector.py
Labels: TO MERGE

#189 bump version to 0.39.0
  setup.py
Labels: Need Review, good first issue

#193 Snowflake :: Add params support
  tests/snowflake/test_snowflake.py
  toucan_connectors/snowflake/snowflake_connector.py
Labels: TO MERGE

#194 chore(bump): bump patch version to 0.39.1
  setup.py
Labels: TO MERGE, enhancement, good first issue

#195 unpin urllib3
  setup.py
Labels: tech

#197 chore(dep): fixing snowflake CI errors
  setup.py
Labels: Need Review, bug, good first issue

#199 chore(deps): bump black and re-lint
  tests/aircall/helpers.py
  tests/aircall/test_aircall.py
  tests/revinate/test_revinate.py
  tests/rok/test_rok.py
  toucan_connectors/__init__.py
  toucan_connectors/aircall/aircall_connector.py
  toucan_connectors/facebook_insights/facebook_insights_connector.py
  toucan_connectors/google_credentials.py
  toucan_connectors/mongo/mongo_connector.py
  toucan_connectors/toucan_connector.py
Labels: Need Review, good first issue
