Repository ToucanToco/toucan-connectors, pull requests merged in 2020-10, with the labels that each got.

#218 build: remove codecov
  .github/workflows/ci.yml
Labels: tech

#216 used convert_to_qmark_paramstyle function in odbc connector
  .github/workflows/ci.yml
  doc/connectors/odbcconnector.md
  requirements-testing.txt
  setup.py
  tests/odbc/test_odbc.py
  tests/test_common.py
  toucan_connectors/__init__.py
  toucan_connectors/common.py
  toucan_connectors/install_scripts/psql.sh
  toucan_connectors/odbc/__init__.py
  toucan_connectors/odbc/odbc.png
  toucan_connectors/odbc/odbc_connector.py
Labels: Need Review

#220 Chore(version): bump-v0.42.0
  setup.py
Labels: Need Review

#219 Update doc generation script
  doc/generate.py
Labels: Need Review

#226 feat(Aircall_oAuthConnector): New Aircall connector using oAuthConnector
  doc/connectors/aircall.md
  doc/connectors/quickstart_aircall.py
  tests/aircall/helpers.py
  tests/aircall/test_aircall.py
  tests/aircall/test_async_funcs.py
  tests/aircall/test_helpers_aircall.py
  toucan_connectors/__init__.py
  toucan_connectors/aircall/Aircall.svg
  toucan_connectors/aircall/aircall_connector.py
  toucan_connectors/oauth2_connector/quickstart/README.md
Labels: Need Review, wip

#222 ROK Connector: Authentication mode with specific JWT
  doc/connectors/ROK.md
  quickstart/rok/quickstart_rok.py
  setup.py
  tests/rok/test_rok.py
  toucan_connectors/rok/rok_connector.py
Labels: Need Review

#232 feat(http connector): Added xml support
  doc/connectors/http_api.md
  requirements-testing.txt
  setup.py
  tests/http_api/test_http_api.py
  toucan_connectors/common.py
  toucan_connectors/http_api/http_api_connector.py
Labels: wip

#247 Update connectors with new pydantic version
  tests/test_connector.py
  toucan_connectors/micro_strategy/micro_strategy_connector.py
Labels: Need Review

#248 feat(odbc-connector): enhanced odbc connector query field
  toucan_connectors/odbc/odbc_connector.py
Labels: enhancement
