Repository ToucanToco/toucan-connectors, pull requests merged in 2020-05, with the labels that each got.

#158 Fix Aircall requests when user is not defined
  tests/aircall/mock_results.py
  tests/aircall/test_helpers.py
  toucan_connectors/aircall/helpers.py
Labels: TO MERGE, bug

#160 bump version to 0.35.0
  setup.py
Labels: TO MERGE, bug

#163 [lint] fix flake8 issues
  setup.py
  tests/oracle_sql/test_oracle_sql.py
  toucan_connectors/aircall/aircall_connector.py
  toucan_connectors/google_my_business/google_my_business_connector.py
  toucan_connectors/micro_strategy/data.py
  toucan_connectors/snowflake/snowflake_connector.py
Labels: TO MERGE, tech

#165 updated to patch version 0.36.1
  setup.py
Labels: Need Review
