Repository ToucanToco/toucan-connectors, pull requests merged in 2020-07, with the labels that each got.

#179 fix(error message) :: ETL validation crash in HTTP connector
  tests/test_common.py
  toucan_connectors/common.py
  toucan_connectors/elasticsearch/elasticsearch_connector.py
  toucan_connectors/http_api/http_api_connector.py
Labels: TO MERGE, bug

#180 versioning :: bumping version to 0.37.4
  setup.py
Labels: Need Review, good first issue

#183 install_scripts :: oracle - add missing wget
  toucan_connectors/install_scripts/oracle.sh
Labels: bug
