Repository ToucanToco/toucan-connectors, pull requests merged in 2020-06, with the labels that each got.

#166 Fix ::: HTTP connector ::: no top level domain
  tests/http_api/test_http_api.py
  toucan_connectors/http_api/http_api_connector.py
Labels: TO MERGE, bug

#167 version bump :: 0.36.2
  setup.py
Labels: Need Review, bug

#170 Trello connector implements "filter" param
  tests/trello/test_trello.py
  toucan_connectors/trello/trello_connector.py
Labels: enhancement

#173 Fix(dependencies) : fixing bug in Github actions
  setup.py
Labels: bug

#172 fix(aircall) : for retrying Aircall API if error
  tests/aircall/test_async_funcs.py
  toucan_connectors/aircall/aircall_connector.py
  toucan_connectors/http_api/http_api_connector.py
Labels: bug

#174 update version to v0.37.1
  setup.py
Labels: Need Review

#176 bump version to 0.37.2
  setup.py
Labels: Need Review

#177 Aircall :: do not collect phone numbers of contacts (GDPR sensible...)
  tests/aircall/mock_results.py
  tests/aircall/test_aircall.py
  tests/aircall/test_helpers.py
  toucan_connectors/aircall/constants.py
  toucan_connectors/aircall/helpers.py
Labels: TO MERGE

#178 bump connector version to 0.37.3
  setup.py
Labels: Need Review
