Repository ToucanToco/toucan-connectors, pull requests merged in 2020-11, with the labels that each got.

#253 docs: added help message to oauth connectors config
  toucan_connectors/aircall/aircall_connector.py
  toucan_connectors/aircall/doc.md
  toucan_connectors/google_sheets_2/doc.md
Labels: wip

#259 fix:MicroStrategy connector accepts empty password
  toucan_connectors/micro_strategy/micro_strategy_connector.py
Labels: fix

#260 chore:bump connectors version to 0.43.14
  setup.py
Labels: chore

#261 refactor:updated gsheet connectors names
  toucan_connectors/__init__.py
Labels: refactor

#262 chore:bump connectors version to 43.15
  setup.py
Labels: chore

#265 fix: increased retry limits and decreased sleeping time
  tests/github/test_github.py
  toucan_connectors/github/github_connector.py
Labels: Need Review

#266 feat(GithubConnector):make organizations available as enum
  tests/github/test_github.py
  toucan_connectors/github/github_connector.py
Labels: Need Review

#269 chore(deps): pin pyodbc to >=3
  setup.py
Labels: Need Review, fix, tech
