Repository ToucanToco/toucan-connectors, pull requests merged in 2020-04, with the labels that each got.

#153 Skip Hive tests temporarly
  tests/hive/test_hive.py
Labels: tech

#152 Set up cache for docker images in CI
  .github/workflows/ci.yml
Labels: tech

#149 f/modified air call
  requirements-testing.txt
  tests/aircall/helpers.py
  tests/aircall/mock_results.py
  tests/aircall/test_aircall.py
  tests/aircall/test_async_funcs.py
  tests/aircall/test_helpers.py
  tests/general_helpers.py
  toucan_connectors/aircall/aircall_connector.py
  toucan_connectors/aircall/constants.py
  toucan_connectors/aircall/helpers.py
  toucan_connectors/common.py
  toucan_connectors/wootric/wootric_connector.py
Labels: TO MERGE, enhancement

#156 Aircall: fix "calls" datasource
  tests/aircall/test_aircall.py
  tests/aircall/test_helpers.py
  toucan_connectors/aircall/helpers.py
Labels: TO MERGE

#157 Bumped version of Toucan Connectors
  requirements-testing.txt
  setup.py
Labels: TO MERGE
