Repository ToucanToco/toucan-connectors, pull requests merged in 2021-01, with the labels that each got.

#289 mssql: support parametrized queries
  tests/mssql/test_mssql.py
  toucan_connectors/mssql/mssql_connector.py
Labels: enhancement

#290 refactor(apply_permissions): make function name explicit
  toucan_connectors/mongo/mongo_connector.py
Labels: Need Review, refactor

#295 fix(doc): links
  toucan_connectors/github/doc.md
  toucan_connectors/google_sheets_2/doc.md
Labels: bug

#291 Improve gsheets connector's form
  setup.py
  tests/google_sheets_2/test_google_sheets_2.py
  toucan_connectors/google_sheets_2/google_sheets_2_connector.py
Labels: wip

#302 feat/salesforce connector
  doc/connectors.md
  doc/connectors/salesforce.md
  setup.py
  tests/salesforce/conftest.py
  tests/salesforce/test_salesforce.py
  toucan_connectors/salesforce/doc.md
  toucan_connectors/salesforce/salesforce.png
  toucan_connectors/salesforce/salesforce_connector.py
Labels: Need Review

#304 fix: Salesforce connector is now in init file
  setup.py
  toucan_connectors/__init__.py
Labels: fix

#306 feat: enable array parameter interpolation in mssql & postgres
  setup.py
  tests/mssql/test_mssql.py
  tests/postgres/test_postgres.py
  tests/test_common.py
  toucan_connectors/common.py
  toucan_connectors/mssql/mssql_connector.py
  toucan_connectors/postgres/postgresql_connector.py
Labels: Need Review

#310 snowflake: Add a default warehouse field
  doc/connectors/snowflake.md
  tests/snowflake/test_snowflake.py
  toucan_connectors/snowflake/snowflake_connector.py
Labels: Need Review

#309 feat(Oracle): Introspection in Oracle Data Source
  tests/oracle_sql/test_oracle_sql.py
  toucan_connectors/oracle_sql/oracle_sql_connector.py
Labels: Need Review
