Repository ToucanToco/toucan-connectors, pull requests merged in 2021-08, with the labels that each got.

#463 fix(use_database_warehouse): add request to use the database and warehouse
  tests/snowflake/test_snowflake.py
  tests/snowflake_oauth2/test_snowflake_oauth2.py
  tests/test_snowflake_common.py
  toucan_connectors/snowflake_common.py
Labels: Need Review, fix

#465 fix(hubspot): update URL and method to get result + remove legacy mode
  tests/hubspot/test_hubspot.py
  toucan_connectors/hubspot/doc.md
  toucan_connectors/hubspot/enums.py
  toucan_connectors/hubspot/hubspot_connector.py
Labels: Need Review

#466 feat(get_identifier): use method to get an unique identifier
  tests/http_api/test_http_api.py
  tests/snowflake/test_snowflake.py
  tests/test_connector.py
  toucan_connectors/snowflake/snowflake_connector.py
  toucan_connectors/snowflake_oauth2/snowflake_oauth2_connector.py
  toucan_connectors/toucan_connector.py
Labels: Need Review

#467 feat(optimize_connection_manager): check if connection use good database and/or warehouse
  tests/snowflake/test_snowflake.py
  tests/snowflake_oauth2/test_snowflake_oauth2.py
  tests/test_snowflake_common.py
  toucan_connectors/snowflake_common.py
Labels: Need Review

#457 fix(duplicate_small_app): update method signature to save secret
  toucan_connectors/oauth2_connector/oauth2connector.py
Labels: wip

#470 chore(bump): upgrade version from 1.2.3 to 1.2.4
  setup.py
Labels: Need Review

#468 feat(google_bigquery_new): new method to retrieve data in bigquery with pandas
  setup.py
  tests/google_big_query/test_google_big_query.py
  toucan_connectors/google_big_query/google_big_query_connector.py
Labels: Need Review

#471 chore(bump): upgrade version to 1.2.5
  setup.py
Labels: Need Review

#473 fix(mysql): support table and query
  tests/mysql/test_mysql.py
  toucan_connectors/mysql/mysql_connector.py
  toucan_connectors/postgres/postgresql_connector.py
Labels: enhancement, Need Review
