Repository ToucanToco/toucan-connectors, pull requests merged in 2021-11, with the labels that each got.

#509 fix(clickhouse): add information_schema db to tests
  tests/clickhouse/test_clickhouse.py
Labels: bug

#508 feat(http): support for custom auth-schemes when using custom_token_server
  tests/test_auth.py
  toucan_connectors/auth.py
Labels: enhancement

#517 test(github): fix extraction dates and correct PR count
  tests/github/conftest.py
  tests/github/test_github.py
Labels: bug, Need Review, tech
