Repository ToucanToco/toucan-connectors, pull requests merged in 2021-05, with the labels that each got.

#393 chores: bump connectors version to 0.52.0
  setup.py
Labels: Need Review

#396 fix: add github connector _oauth_trigger attribute
  toucan_connectors/github/github_connector.py
  toucan_connectors/toucan_connector.py
Labels: Need Review

#397 chores(versions): bump connectors version 0.52.1
  setup.py
Labels: Need Review

#387 feat(snowflakeconnector): format snowflake connector form
  requirements-testing.txt
  setup.py
  tests/snowflake/test_snowflake.py
  toucan_connectors/snowflake/snowflake_connector.py
  toucan_connectors/toucan_connector.py
Labels: Need Review

#407 fix(hubspot): Add Class JsonWrapper to replace all import json by thi…
  doc/connectors/google_my_business.md
  quickstart/aircall/helpers.py
  quickstart/github/helpers.py
  quickstart/google_sheets_2/helpers.py
  quickstart/rok/quickstart_rok.py
  tests/fixtures/json.json
  tests/google_analytics/test_google_analytics.py
  tests/google_sheets_2/test_google_sheets_2.py
  tests/http_api/test_http_api.py
  tests/micro_strategy/test_microstrategy.py
  tests/mongo/test_mongo.py
  tests/oauth2_connector/test_oauth2connector.py
  tests/rok/test_rok.py
  tests/snowflake/test_snowflake.py
  tests/soap/test_soap.py
  tests/test_json_wrapper.py
  tests/trello/test_trello.py
  toucan_connectors/json_wrapper.py
  toucan_connectors/mongo/mongo_connector.py
  toucan_connectors/oauth2_connector/oauth2connector.py
  toucan_connectors/rok/rok_connector.py
  toucan_connectors/wootric/wootric_connector.py
Labels: fix

#412 fix(dependencies): pyjq from 2.5.1 to 2.5.2
  setup.py
Labels: Need Review

#409 feat(snowflake): use new tokens and secrets forwarded from caller
  setup.py
  tests/snowflake/test_snowflake.py
  toucan_connectors/snowflake/snowflake_connector.py
Labels: enhancement

#416 fix(snowflakes): change category to snowflake
  setup.py
  toucan_connectors/snowflake/snowflake_connector.py
  toucan_connectors/snowflake_oauth2/snowflake_oauth2_connector.py
  toucan_connectors/toucan_connector.py
Labels: Need Review

#418 Fix/dependencies
  setup.py
Labels: Need Review
