Repository ToucanToco/toucan-connectors, pull requests merged in 2021-06, with the labels that each got.

#429 Fix/mssql tl sv1 0
  setup.py
  toucan_connectors/install_scripts/mssql_TLSv1_0.sh
Labels: Need Review

#428 One Drive Connector
  doc/connectors.md
  doc/connectors/one_drive.md
  tests/one_drive/test_one_drive.py
  toucan_connectors/__init__.py
  toucan_connectors/one_drive/one_drive.png
  toucan_connectors/one_drive/one_drive_connector.py
Labels: Need Review

#433 Feat/google big query
  tests/google_big_query/test_google_big_query.py
  toucan_connectors/common.py
  toucan_connectors/google_big_query/google_big_query_connector.py
Labels: Need Review

#435 chore(bump connectors): 0.55.3
  setup.py
Labels: Need Review

#437 fix: handle datetime 0000-00-00 in mysql connector
  tests/mysql/test_mysql.py
  toucan_connectors/mysql/mysql_connector.py
Labels: bug

#426 Azure mssql parametrization
  setup.py
  tests/azure_mssql/test_azure_mssql.py
  toucan_connectors/azure_mssql/azure_mssql_connector.py
Labels: enhancement
