Repository ToucanToco/toucan-connectors, pull requests merged in 2021-09, with the labels that each got.

#480 fix(snowflake common): fix describe result logging
  setup.py
  tests/test_snowflake_common.py
  toucan_connectors/snowflake_common.py
Labels: Need Review, fix

#481 odbc-oracle :: use public packages toucan
  setup.py
  toucan_connectors/install_scripts/odbc.sh
  toucan_connectors/install_scripts/oracle.sh
Labels: dependencies

#482 fix(multiple_queries): remove multiple queries one execute
  tests/snowflake/test_snowflake.py
  tests/snowflake_oauth2/test_snowflake_oauth2.py
  tests/test_snowflake_common.py
  toucan_connectors/snowflake_common.py
Labels: bug, Need Review

#483 chore(bump): upgrade to 1.2.9
  setup.py
Labels: Need Review

#485 feat(models): better cache_ttl title & description
  Makefile
  tests/test_datasource.py
  toucan_connectors/toucan_connector.py
Labels: enhancement, Need Review

#489 fix: add database & warehouse in snowflake's connection key
  setup.py
  toucan_connectors/snowflake/snowflake_connector.py
  toucan_connectors/snowflake_oauth2/snowflake_oauth2_connector.py
Labels: fix

#492 fix: wrong type name in snowflake_common
  setup.py
  toucan_connectors/snowflake_common.py
Labels: Need Review

#494 fix(snowflake_common): type mapping
  setup.py
  tests/test_snowflake_common.py
  toucan_connectors/snowflake_common.py
Labels: Need Review, fix
