Repository ToucanToco/toucan-connectors, pull requests merged in 2021-04, with the labels that each got.

#363 fix(soap connector): serialize response to handle return format
  setup.py
  tests/conftest.py
  tests/soap/test_soap.py
  toucan_connectors/soap/soap_connector.py
Labels: Need Review

#365 feat(facebook ads): Add insights endpoint
  doc/connectors/facebook_ads.md
  tests/facebook_ads/test_facebook_ads.py
  toucan_connectors/facebook_ads/enums.py
  toucan_connectors/facebook_ads/facebook_ads_connector.py
Labels: enhancement

#364 chore(http-api): update datasource keys order
  tests/http_api/test_http_api.py
  toucan_connectors/http_api/http_api_connector.py
Labels: Need Review, chore

#367 chore(version): bump-v0.51.6
  setup.py
Labels: tech

#368 feat(sql connectors): convert basic jinja to printf templating style
  tests/postgres/test_postgres.py
  tests/test_common.py
  toucan_connectors/azure_mssql/azure_mssql_connector.py
  toucan_connectors/clickhouse/clickhouse_connector.py
  toucan_connectors/common.py
  toucan_connectors/google_cloud_mysql/google_cloud_mysql_connector.py
  toucan_connectors/mssql/mssql_connector.py
  toucan_connectors/mysql/mysql_connector.py
  toucan_connectors/odbc/odbc_connector.py
  toucan_connectors/oracle_sql/oracle_sql_connector.py
  toucan_connectors/postgres/postgresql_connector.py
  toucan_connectors/sap_hana/sap_hana_connector.py
Labels: enhancement

#371 fix(nosql apply parameters to query): keep str type when appropriate
  setup.py
  tests/test_common.py
  toucan_connectors/common.py
Labels: Need Review, bug

#369 refactor(sql connectors): add util pandas_read_sql
  tests/azure_mssql/test_azure_mssql.py
  tests/google_cloud_mysql/test_google_cloud_mysql.py
  tests/mysql/test_mysql.py
  tests/oracle_sql/test_oracle_sql.py
  tests/postgres/test_postgres.py
  tests/sap_hana/test_sap_hana.py
  tests/test_common.py
  toucan_connectors/azure_mssql/azure_mssql_connector.py
  toucan_connectors/clickhouse/clickhouse_connector.py
  toucan_connectors/common.py
  toucan_connectors/google_cloud_mysql/google_cloud_mysql_connector.py
  toucan_connectors/mssql/mssql_connector.py
  toucan_connectors/mysql/mysql_connector.py
  toucan_connectors/odbc/odbc_connector.py
  toucan_connectors/oracle_sql/oracle_sql_connector.py
  toucan_connectors/postgres/postgresql_connector.py
  toucan_connectors/sap_hana/sap_hana_connector.py
Labels: refactor

#372 feat(snowflake): make the snowflake connector be able to test its connectivity
  tests/snowflake/test_snowflake.py
  toucan_connectors/snowflake/snowflake_connector.py
Labels: enhancement

#375 chore(version): bump v0.51.9
  setup.py
Labels: Need Review, chore

#376 fix(snowflake): improve verbosity of get_status
  tests/snowflake/test_snowflake.py
  toucan_connectors/snowflake/snowflake_connector.py
Labels: Need Review, fix

#383 fix(snowflake): fix snowflake parametrization
  setup.py
  tests/snowflake/test_snowflake.py
  tests/test_common.py
  toucan_connectors/common.py
  toucan_connectors/snowflake/snowflake_connector.py
Labels: bug

#382 feat: add secrets_storage_version attribute
  setup.py
  toucan_connectors/toucan_connector.py
Labels: Need Review

#385 chore(version): bump v0.51.13
  setup.py
Labels: Need Review, chore

#386 fix: typo in gsheet connector
  setup.py
  tests/google_sheets_2/test_google_sheets_2.py
  toucan_connectors/google_sheets_2/google_sheets_2_connector.py
Labels: Need Review, bug
