Repository ToucanToco/toucan-connectors, pull requests merged in 2021-03, with the labels that each got.

#350 fix(snowflake): convert parameters to qmark style
  tests/snowflake/test_snowflake.py
  toucan_connectors/snowflake/snowflake_connector.py
Labels: bug

#349 feat: Facebook ads connector
  doc/connectors/facebook_ads.md
  tests/facebook_ads/test_facebook_ads.py
  toucan_connectors/__init__.py
  toucan_connectors/facebook_ads/__init__.py
  toucan_connectors/facebook_ads/doc.md
  toucan_connectors/facebook_ads/enums.py
  toucan_connectors/facebook_ads/facebook_ads_connector.py
  toucan_connectors/facebook_ads/facebook_logo.png
  toucan_connectors/facebook_ads/helpers.py
Labels: Need Review

#354 feat: flatten rendred nested lists in nosql_apply_parameters_to_query
  setup.py
  tests/test_common.py
  toucan_connectors/common.py
Labels: enhancement

#357 fix: pin python snowflake connector version
  setup.py
Labels: dependencies

#358 chore(version): bump version to 0.51.1
  setup.py
Labels: chore
