Repository ToucanToco/toucan-connectors, pull requests merged in 2021-07, with the labels that each got.

#448 feat(metadata): add metadata in DataSlice
  doc/metadata.md
  tests/aircall/test_aircall.py
  tests/github/test_github.py
  tests/google_sheets_2/test_google_sheets_2.py
  tests/mongo/test_mongo.py
  tests/soap/test_soap.py
  tests/test_connector.py
  toucan_connectors/mongo/mongo_connector.py
  toucan_connectors/toucan_connector.py
Labels: Need Review

#451 Feat(fetch_many): create a "sup" query around the query in parameters
  doc/metadata.md
  setup.py
  tests/fixtures/fixture_query_manager/data.json
  tests/snowflake_oauth2/test_snowflake_oauth2.py
  tests/test_common.py
  tests/test_connection_manager.py
  tests/test_query_manager.py
  tests/test_snowflake_common.py
  tests/test_sql_query_helper.py
  toucan_connectors/common.py
  toucan_connectors/connection_manager.py
  toucan_connectors/query_manager.py
  toucan_connectors/snowflake/snowflake_connector.py
  toucan_connectors/snowflake_common.py
  toucan_connectors/sql_query_helper.py
Labels: Need Review

#452 Feat(snowflake): simplify connection_manager
  setup.py
  tests/test_connection_manager.py
  tests/test_query_manager.py
  tests/test_snowflake_common.py
  toucan_connectors/connection_manager.py
  toucan_connectors/query_manager.py
  toucan_connectors/snowflake_common.py
Labels: wip

#443 feat(query_pool): add new object to store connection
  doc/connection_manager.md
  doc/metadata.md
  setup.py
  tests/fixtures/fixture_query_manager/data.json
  tests/fixtures/fixture_snowflake_common/data_10.json
  tests/fixtures/fixture_snowflake_common/data_5.json
  tests/oauth2_connector/test_oauth2connector.py
  tests/snowflake/fixture/data.json
  tests/snowflake/test_snowflake.py
  tests/snowflake_oauth2/fixture/data.json
  tests/snowflake_oauth2/test_snowflake_oauth2.py
  tests/test_connection_manager.py
  tests/test_connector.py
  tests/test_query_manager.py
  tests/test_snowflake_common.py
  tests/test_sql_query_helper.py
  toucan_connectors/connection_manager.py
  toucan_connectors/google_big_query/google_big_query_connector.py
  toucan_connectors/oauth2_connector/oauth2connector.py
  toucan_connectors/query_manager.py
  toucan_connectors/snowflake/snowflake_connector.py
  toucan_connectors/snowflake_common.py
  toucan_connectors/snowflake_oauth2/snowflake_oauth2_connector.py
  toucan_connectors/sql_query_helper.py
  toucan_connectors/toucan_connector.py
Labels: Need Review

#458 feat: add get_cache_key method for queries caching
  tests/http_api/test_http_api.py
  tests/test_connector.py
  toucan_connectors/toucan_connector.py
Labels: enhancement

#460 feat: add `cache_ttl` field on ToucanConnector and ToucanDataSource
  setup.py
  tests/http_api/test_http_api.py
  tests/mongo/test_mongo.py
  tests/test_connector.py
  tests/test_datasource.py
  toucan_connectors/mongo/mongo_connector.py
  toucan_connectors/toucan_connector.py
Labels: enhancement

#456 Adding new fields to OneDriveDatasource in order to enable connection with SharePoint workbooks
  tests/one_drive/test_one_drive.py
  toucan_connectors/__init__.py
  toucan_connectors/one_drive/one_drive.png
  toucan_connectors/one_drive/one_drive_connector.py
  toucan_connectors/share_point/share_point.png
Labels: Need Review

#461 feat: add describe method & associated objects in connectors
  setup.py
  tests/snowflake/test_snowflake.py
  tests/snowflake_oauth2/test_snowflake_oauth2.py
  tests/test_query_manager.py
  tests/test_snowflake_common.py
  toucan_connectors/query_manager.py
  toucan_connectors/snowflake/snowflake_connector.py
  toucan_connectors/snowflake_common.py
  toucan_connectors/snowflake_oauth2/snowflake_oauth2_connector.py
  toucan_connectors/toucan_connector.py
Labels: wip
