Repository ToucanToco/toucan-connectors, pull requests merged in 2022-06, with the labels that each got.

#605 chore: bump awswrangler to support pandas >=1.3
  setup.py
  sonar-project.properties
Labels: dependencies

#606 chore: Move to poetry TCTC-2931
  .flake8
  .github/workflows/ci.yml
  Makefile
  README.md
  poetry.lock
  pyproject.toml
  requirements-testing.txt
  setup.py
Labels: dependencies

#552 doc: add simple contributing guidelines
  README.md
Labels: doc

#609 feat: add support for elasticsearch 8 [TCTC-1907]
  doc/connectors/elasticsearch.md
  poetry.lock
  pyproject.toml
  tests/docker-compose.yml
  tests/elasticsearch/test_elasticsearch.py
  toucan_connectors/elasticsearch/elasticsearch_connector.py
Labels: Need Review

#611 chore: bump from 3.10 to 3.11
  CHANGELOG.md
  pyproject.toml
Labels: Need Review

#614 Chore/update redshift
  tests/redshift/test_redshift.py
  toucan_connectors/redshift/redshift_database_connector.py
Labels: Need Review

#615 chore: v3.12.0
  CHANGELOG.md
  poetry.lock
  pyproject.toml
Labels: Need Review

#616 feat: default db check for postgres and redshift
  tests/postgres/test_postgres.py
  tests/redshift/test_redshift.py
  toucan_connectors/postgres/postgresql_connector.py
  toucan_connectors/redshift/redshift_database_connector.py
Labels: Need Review

#617 chore: bump toucan-connectors from 3.12.0 to 3.13.0
  CHANGELOG.md
  pyproject.toml
Labels: Need Review

#620 feat(discoverable gbq): get db model TCTC-3092
  tests/google_big_query/test_google_big_query.py
  toucan_connectors/google_big_query/google_big_query_connector.py
Labels: wip

#622 v3.15.0
  CHANGELOG.md
  pyproject.toml
  sonar-project.properties
Labels: Need Review

#623 chore(big query): add database attribute in datasource tctc-3092
  tests/google_big_query/test_google_big_query.py
  toucan_connectors/google_big_query/google_big_query_connector.py
Labels: Need Review

#625 fix(bigquery): ignore database extra attribute
  toucan_connectors/google_big_query/google_big_query_connector.py
Labels: Need Review

#626 chore: bump connectors 3.15.2
  CHANGELOG.md
  pyproject.toml
  sonar-project.properties
Labels: Need Review
