Repository ToucanToco/toucan-connectors, pull requests merged in 2022-09, with the labels that each got.

#659 deps: remove werkzeug (BadRequest) dependency [TCTC-3805]
  poetry.lock
  pyproject.toml
  tests/databricks/test_databricks.py
  toucan_connectors/common.py
  toucan_connectors/databricks/databricks_connector.py
Labels: Need Review

#660 chore: bump from 3.19.0 to 3.20.1
  CHANGELOG.md
  pyproject.toml
Labels: Need Review

#663 feat: remove "_id" column from DataFrame on mongo_connector [TC-3788]
  CHANGELOG.md
  pyproject.toml
  tests/mongo/test_mongo.py
  toucan_connectors/mongo/mongo_connector.py
Labels: Need Review

#664 fix(athena): Fix pagination values TCTC-3822
  tests/awsathena/test_awsathena.py
  tests/test_connector.py
  toucan_connectors/awsathena/awsathena_connector.py
  toucan_connectors/toucan_connector.py
Labels: Need Review, fix

#665 chore: v3.20.3
  CHANGELOG.md
  pyproject.toml
Labels: Need Review, chore

#666 [Athena] missing ; for variables
  tests/awsathena/test_awsathena.py
  toucan_connectors/awsathena/awsathena_connector.py
Labels: Need Review

#669 fix: bigQuery variables interpolation [TCTC-3642]
  tests/google_big_query/test_google_big_query.py
  toucan_connectors/google_big_query/google_big_query_connector.py
Labels: Need Review

#670 chore: bump from 3.20.5 to 3.20.6
  poetry.lock
  pyproject.toml
Labels: Need Review

#672 feat(mysql): Add support for SSL TCTC-3184
  doc/connectors/mysql.md
  poetry.lock
  pyproject.toml
  tests/mysql/test_mysql.py
  tests/utils/fixtures/pem_key_with_spaces.pem
  tests/utils/fixtures/sanitized_pem_key.pem
  tests/utils/test_pem.py
  toucan_connectors/mysql/mysql_connector.py
  toucan_connectors/utils/pem.py
Labels: enhancement, Need Review

#673 chore: v3.21.0
  CHANGELOG.md
  pyproject.toml
Labels: Need Review, chore

#675 chore(ci): Set up PyPI release automation + dependabot TCTC-1590
  .github/dependabot.yml
  .github/workflows/publish.yml
Labels: Need Review, tech, chore

#694 chore: v3.21.1
  CHANGELOG.md
  pyproject.toml
Labels: Need Review

#610 feat: get version of toucan-connector
  toucan_connectors/__init__.py
Labels: Need Review

#695 chore: bump snowflake-connector-python to 2.7.12
  poetry.lock
  pyproject.toml
Labels: Need Review, chore, dependencies

#698 doc: Update "Publishing" section of README
  README.md
Labels: doc, Need Review

#699 chore: v3.22.0
  CHANGELOG.md
  pyproject.toml
Labels: Need Review, chore

#701 fix(utils): Pass utc=True in sanitize_df_dates util
  tests/google_sheets/test_google_sheets.py
  tests/google_sheets_2/test_google_sheets_2.py
  tests/one_drive/test_one_drive.py
  tests/utils/test_datetime.py
  toucan_connectors/utils/datetime.py
Labels: bug, Need Review

#704 chore: v3.22.2
  CHANGELOG.md
  pyproject.toml
Labels: Need Review, chore

#662 feat: get target version per engine [TCTC-3498]
  tests/mongo/test_mongo.py
  tests/mysql/test_mysql.py
  tests/postgres/test_postgres.py
  tests/test_connector.py
  toucan_connectors/mongo/mongo_connector.py
  toucan_connectors/mysql/mysql_connector.py
  toucan_connectors/postgres/postgresql_connector.py
  toucan_connectors/toucan_connector.py
Labels: Need Review
