Repository ToucanToco/toucan-connectors, pull requests merged in 2022-02, with the labels that each got.

#556 feat(google-sheets): implement get_status for new google-sheets connector TCTC-1672
  tests/google_sheets/test_google_sheets.py
  tests/google_sheets/user-infos.json
  toucan_connectors/google_sheets/google_sheets_connector.py
Labels: Need Review

#557 doc(google-sheets): document list_sheets method
  doc/connectors/google_sheets.md
Labels: doc

#558 fix(google-sheets): pass service id in connector infos
  tests/google_sheets/test_google_sheets.py
  toucan_connectors/__init__.py
  toucan_connectors/google_sheets/google_sheets_connector.py
  toucan_connectors/toucan_connector.py
Labels: fix

#560 feat(google-sheets): order fields & list available sheets in datasource form TCTC-1819
  setup.py
  sonar-project.properties
  tests/google_sheets/test_google_sheets.py
  toucan_connectors/google_sheets/google_sheets_connector.py
Labels: enhancement, Need Review

#562 feat(google-sheets): update connector labels TCTC-1845
  toucan_connectors/__init__.py
Labels: enhancement, Need Review

#563 chore(PG, SF, RS): add language & query_object attributes [TCTC-1715]
  tests/postgres/test_postgres.py
  tests/redshift/test_redshift.py
  tests/snowflake/test_snowflake.py
  toucan_connectors/postgres/postgresql_connector.py
  toucan_connectors/redshift/redshift_database_connector.py
  toucan_connectors/snowflake_common.py
Labels: Need Review

#567 chores(version): bump to 3.1.2
  setup.py
  sonar-project.properties
Labels: chore

#569 fix(postgres): format all result from get model
  setup.py
  sonar-project.properties
  toucan_connectors/postgres/postgresql_connector.py
Labels: bug

#571 fix(redshift): filter duplicate sys table from get-model query
  setup.py
  sonar-project.properties
  toucan_connectors/redshift/redshift_database_connector.py
Labels: Need Review

#574 fix(snowflake): get model query
  setup.py
  sonar-project.properties
  toucan_connectors/snowflake_common.py
Labels: Need Review
