Repository ToucanToco/toucan-connectors, pull requests merged in 2022-05, with the labels that each got.

#594 feat(google BigQuery): Add support for array query parameters TCTC-1447
  tests/google_big_query/test_google_big_query.py
  toucan_connectors/google_big_query/google_big_query_connector.py
Labels: enhancement, TO MERGE

#590 feat(googlebigquery): parse dates as datetime dtype [TCTC-2521]
  toucan_connectors/google_big_query/google_big_query_connector.py
Labels: bug

#598 fix: dependencies (accordingly to laputa) [TCTC-2752]
  Makefile
  setup.py
  sonar-project.properties
Labels: Need Review

#600 fix: http api json decode error
  setup.py
  sonar-project.properties
  tests/http_api/test_http_api.py
  toucan_connectors/http_api/http_api_connector.py
Labels: Need Review

#603 feat(mongo-connector): allow search on multiple columns [TCTC-2532]
  tests/mongo/fixtures/docs.json
  tests/mongo/test_mongo.py
  toucan_connectors/mongo/mongo_connector.py
Labels: enhancement
