Repository ToucanToco/toucan-connectors, pull requests merged in 2022-10, with the labels that each got.

#715 fix/alphanumeric percentage only
  tests/mysql/test_mysql.py
  toucan_connectors/common.py
Labels: bug, Need Review

#716 chore:v3.23.1
  CHANGELOG.md
  pyproject.toml
  sonar-project.properties
Labels: Need Review

#722 fix(common): Add support for __VOID__ to nosql_apply_parameters_to_query TCTC-4267
  CHANGELOG.md
  tests/mongo/test_mongo.py
  tests/test_common.py
  toucan_connectors/common.py
  toucan_connectors/mongo/mongo_connector.py
Labels: Need Review, fix

#738 chore: v3.23.3
  CHANGELOG.md
  pyproject.toml
  sonar-project.properties
Labels: Need Review, chore

#739 fix(mongo): Do not remove matches on null in normalize_query (#737) [backport]
  CHANGELOG.md
  tests/mongo/test_mongo.py
  toucan_connectors/mongo/mongo_connector.py
Labels: Need Review, chore

#741 chore(ci): Add dependabot on GH actions
  .github/dependabot.yml
Labels: Need Review, chore

#742 chore: v3.23.4
  CHANGELOG.md
  pyproject.toml
  sonar-project.properties
Labels: TO MERGE, chore

#743 fix(postgresql): Ensure we always use default_database if provided TCTC-4462 (#740) [backport]
  CHANGELOG.md
  tests/postgres/test_postgres.py
  toucan_connectors/postgres/postgresql_connector.py
Labels: TO MERGE, chore
