Repository ToucanToco/toucan-connectors, pull requests merged in 2022-08, with the labels that each got.

#646 feat(athena): Add an option allowing to toggle CTAS
  CHANGELOG.md
  doc/connectors.md
  doc/connectors/awsathena.md
  tests/awsathena/test_awsathena.py
  toucan_connectors/awsathena/awsathena_connector.py
Labels: enhancement, Need Review

#649 fix: sanitize sql for athena connector
  tests/awsathena/test_awsathena.py
  tests/test_common.py
  toucan_connectors/awsathena/awsathena_connector.py
  toucan_connectors/common.py
Labels: bug, Need Review

#651 chore: v3.18.2
  CHANGELOG.md
  pyproject.toml
Labels: Need Review, chore

#655 fix(mysql): Always specify db_name in get_model TCTC-3769
  tests/mysql/test_mysql.py
  tests/test_connector.py
  toucan_connectors/awsathena/awsathena_connector.py
  toucan_connectors/google_big_query/google_big_query_connector.py
  toucan_connectors/mysql/mysql_connector.py
  toucan_connectors/postgres/postgresql_connector.py
  toucan_connectors/redshift/redshift_database_connector.py
  toucan_connectors/snowflake/snowflake_connector.py
  toucan_connectors/snowflake_oauth2/snowflake_oauth2_connector.py
  toucan_connectors/toucan_connector.py
Labels: bug, Need Review, refactor

#654 feat(redshift): Add an option to toggle TCP keep-alive (enabled by default) TCTC-3769
  tests/redshift/test_redshift.py
  toucan_connectors/redshift/redshift_database_connector.py
Labels: enhancement, Need Review

#657 fix(mysql): Do not use too modern aggregation functions when retrieving project structure TCTC-3768
  tests/mysql/test_mysql.py
  toucan_connectors/mysql/mysql_connector.py
Labels: bug, Need Review

#656 chore: v3.19.0
  CHANGELOG.md
  pyproject.toml
Labels: chore
