Repository ToucanToco/toucan-connectors, pull requests merged in 2022-07, with the labels that each got.

#627 Redshift connector does not work with ConnectionManager
  tests/redshift/test_redshift.py
  toucan_connectors/redshift/redshift_database_connector.py
Labels: Need Review

#631 feat: multi-column filtering [TCTC-3332]
  tests/mongo/test_mongo.py
  toucan_connectors/mongo/mongo_connector.py
Labels: enhancement, Need Review

#632 chore: v3.16.0
  CHANGELOG.md
  pyproject.toml
Labels: Need Review, chore

#633 feat(athena): graphical interface
  tests/awsathena/test_awsathena.py
  toucan_connectors/awsathena/awsathena_connector.py
Labels: Need Review

#636 feat(mysql): graphical selection
  tests/docker-compose.yml
  tests/mysql/fixtures/world.sql
  tests/mysql/test_mysql.py
  toucan_connectors/mysql/mysql_connector.py
Labels: Need Review

#639 fix: Ensure STL dates are returned with the right dtype TCTC-3424
  tests/utils/test_datetime.py
  toucan_connectors/toucan_connector.py
  toucan_connectors/utils/__init__.py
  toucan_connectors/utils/datetime.py
Labels: bug, Need Review
