Repository ToucanToco/toucan-connectors, pull requests merged in 2022-12, with the labels that each got.

#800 fix: google-sheet dates load double to string [TCTC-4148]
  CHANGELOG.md
  toucan_connectors/google_sheets/google_sheets_connector.py
Labels: Need Review

#801 chore: bump toucan-connectors from 3.23.5 to 3.23.6
  CHANGELOG.md
  pyproject.toml
  sonar-project.properties
Labels: Need Review

#802 feat: add an option to render date-time when reading a sheet
  CHANGELOG.md
  toucan_connectors/google_sheets/google_sheets_connector.py
Labels: Need Review

#810 Revert "build(deps-dev): bump pytest-rerunfailures from 10.2 to 10.3"
  poetry.lock
  pyproject.toml
Labels: Need Review, chore

#814 chore: bump connectors from 3.23.6 to 3.23.7
  CHANGELOG.md
  pyproject.toml
  sonar-project.properties
Labels: Need Review

#813 feat: we want the date-as-float selected as default
  CHANGELOG.md
  toucan_connectors/google_sheets/google_sheets_connector.py
Labels: Need Review

#847 fix(gbq): Support building a DB model for projects with datasets in distinct locations TCTC-4879
  CHANGELOG.md
  tests/google_big_query/test_google_big_query.py
  toucan_connectors/google_big_query/google_big_query_connector.py
Labels: bug

#848 chore(server): v3.23.8
  CHANGELOG.md
  poetry.lock
  pyproject.toml
  sonar-project.properties
Labels: chore
