Repository ToucanToco/toucan-connectors, pull requests merged in 2022-04, with the labels that each got.

#581 build: fix linting
  .devcontainer/devcontainer.json
  .github/workflows/ci.yml
  .pre-commit-config.yaml
  README.md
  doc/DataSlice.md
  doc/connection_manager.md
  doc/connectors/ROK.md
  doc/connectors/salesforce.md
  doc/generate.py
  quickstart/aircall/quickstart.py
  quickstart/github/quickstart.py
  quickstart/rok/quickstart_rok.py
  requirements-testing.txt
  tests/fixtures/fixture_snowflake_common/data_10.json
  tests/fixtures/fixture_snowflake_common/data_5.json
  tests/snowflake/fixture/data.json
  tests/snowflake_oauth2/fixture/data.json
  toucan_connectors/aircall/Aircall.svg
  toucan_connectors/aircall/doc.md
  toucan_connectors/github/doc.md
  toucan_connectors/google_adwords/doc.md
  toucan_connectors/google_sheets_2/doc.md
  toucan_connectors/linkedinads/doc.md
  toucan_connectors/salesforce/doc.md
  toucan_connectors/salesforce_sandbox/doc.md
Labels: Need Review, tech

#585 Feat: Add AWS Athena connector TCTC-2427
  doc/connectors/awsathena.md
  doc/generate.py
  setup.py
  tests/awsathena/fixtures/beers.csv
  tests/awsathena/test_awsathena.py
  toucan_connectors/__init__.py
  toucan_connectors/awsathena/__init__.py
  toucan_connectors/awsathena/athena.png
  toucan_connectors/awsathena/awsathena_connector.py
Labels: enhancement, Need Review

#589 fix: databricks get status
  setup.py
  sonar-project.properties
  tests/databricks/test_databricks.py
  toucan_connectors/databricks/databricks_connector.py
Labels: Need Review
