Repository ToucanToco/toucan-connectors, pull requests merged in 2022-01, with the labels that each got.

#541 chore: v1.3.39
  setup.py
  sonar-project.properties
Labels: Need Review

#542 fix(postgres): not using hostname any more (host is enough) TCTC-1603
  doc/connectors/postgres.md
  setup.py
  sonar-project.properties
  tests/postgres/test_postgres.py
  toucan_connectors/postgres/postgresql_connector.py
Labels: bug

#543 fix(sql): get row count for queries using aggregation methods TCTC-1567
  tests/redshift/test_redshift.py
  tests/test_sql_query_helper.py
  toucan_connectors/redshift/redshift_database_connector.py
  toucan_connectors/snowflake_common.py
  toucan_connectors/sql_query_helper.py
Labels: Need Review, fix

#544 chore(release): v1.3.41
  setup.py
  sonar-project.properties
Labels: chore

#545 fix(sql): don't run count for DESCRIBE or SHOW queries TCTC-1567
  setup.py
  sonar-project.properties
  tests/redshift/test_redshift.py
  tests/test_sql_query_helper.py
  toucan_connectors/redshift/redshift_database_connector.py
  toucan_connectors/snowflake_common.py
  toucan_connectors/sql_query_helper.py
Labels: Need Review, fix

#549 Add .devcontainer definition
  .devcontainer/Dockerfile
  .devcontainer/devcontainer.json
  README.md
  tests/conftest.py
Labels: Need Review

#550 feat(onedrive, sharepoint): add filenames_to_match param to extract m…
  setup.py
  sonar-project.properties
  tests/one_drive/test_one_drive.py
  toucan_connectors/one_drive/one_drive_connector.py
Labels: Need Review

#546 doc: format the DataStats model [TCTC-1417]
  doc/DataSlice.md
  toucan_connectors/snowflake_common.py
  toucan_connectors/toucan_connector.py
Labels: Need Review

#551 chore: bump from 1.3.43 to 2.0.0
  CHANGELOG.md
  setup.py
  sonar-project.properties
Labels: Need Review

#554 fix(sql): pandas read_sql needs SQLAlchemy
  setup.py
Labels: tech, dependencies
