Repository ToucanToco/toucan-connectors, pull requests merged in 2023-10, with the labels that each got.

#1308 fix: get good project_id from jwt or google-creds when they are set or not [TCTC-6942]
  CHANGELOG.md
  tests/google_big_query/test_google_big_query.py
  toucan_connectors/google_big_query/google_big_query_connector.py
Labels: Need Review

#1310 chore: bump 4.9.1 to 4.9.2
  CHANGELOG.md
  pyproject.toml
  sonar-project.properties
Labels: Need Review

#1319 fix: CI error on installs with msgpack :
  poetry.lock
Labels: Need Review

#1331 fix(3.23, snowflake): pin oscrypto to solve ongoing issue with OpenSSL 3.10
  CHANGELOG.md
  poetry.lock
  pyproject.toml
Labels: Need Review, fix

#1333 ci: v4.9.3
  CHANGELOG.md
  pyproject.toml
  sonar-project.properties
Labels: Need Review

#1332 ci: v3.23.19
  CHANGELOG.md
  pyproject.toml
  sonar-project.properties
Labels: Need Review

#1248 fix: fix mssql install scripts by forcing debian/11 deb repo
  CHANGELOG.md
  toucan_connectors/install_scripts/mssql.sh
  toucan_connectors/install_scripts/mssql_TLSv1_0.sh
Labels: bug

#1344 fix(databricks): update databricks ODBC connector
  toucan_connectors/databricks/databricks_connector.py
  toucan_connectors/install_scripts/databricks.sh
Labels: Need Review, dependencies

#1346 chore: v4.9.4
  pyproject.toml
  sonar-project.properties
Labels: chore

#1347 chore: v3.23.21
  CHANGELOG.md
  poetry.lock
  pyproject.toml
  sonar-project.properties
Labels: bug, Need Review, dependencies
