Repository ToucanToco/toucan-connectors, pull requests merged in 2023-09, with the labels that each got.

#1258 chore(deps): Pin numpy<1.24
  poetry.lock
  pyproject.toml
  tests/test_numpy_version.py
Labels: bug, Need Review, dependencies

#1259 chore: v3.23.18
  CHANGELOG.md
  pyproject.toml
  sonar-project.properties
Labels: Need Review

#1273 feat: add s3 connector TCTC-6566
  doc/connectors/s3.md
  tests/s3/test_s3.py
  toucan_connectors/__init__.py
  toucan_connectors/s3/__init__.py
  toucan_connectors/s3/s3.png
  toucan_connectors/s3/s3_connector.py
Labels: enhancement, Need Review

#1286 chore: v4.8.1
  CHANGELOG.md
  pyproject.toml
  sonar-project.properties
Labels: Need Review

#1287 feat: add support for JWT connexion on GoogleBigQuery connector [TCTC-6756]
  CHANGELOG.md
  doc/connectors/google_big_query.md
  tests/google_big_query/test_google_big_query.py
  toucan_connectors/google_big_query/google_big_query_connector.py
  toucan_connectors/google_credentials.py
Labels: enhancement, Need Review

#1291 chore: bump from 4.8.1 to 4.9.0
  CHANGELOG.md
  pyproject.toml
  sonar-project.properties
Labels: Need Review

#1293 fix(gbq): Validation error on mandatory GoogleCreds missing + add descriptive Exception message on missing datas [TCTC-6756]
  CHANGELOG.md
  doc/connectors/google_big_query.md
  tests/google_big_query/test_google_big_query.py
  toucan_connectors/google_big_query/google_big_query_connector.py
  toucan_connectors/google_credentials.py
Labels: Need Review

#1295 chore: bump from 4.9.0 to 4.9.1
  CHANGELOG.md
  pyproject.toml
  sonar-project.properties
Labels: Need Review
