Repository ToucanToco/toucan-connectors, pull requests merged in 2023-08, with the labels that each got.

#1215 feat(backport): google big query database selection much faster [TCTC-6113] (#1126) [TCTC-6473]
  CHANGELOG.md
  tests/google_big_query/test_google_big_query.py
  toucan_connectors/google_big_query/google_big_query_connector.py
Labels: Need Review

#1217 chore: bump from v3.23.15 to 3.23.16 [TCTC-6473]
  CHANGELOG.md
  pyproject.toml
  sonar-project.properties
Labels: Need Review

#1228 fix: replace empty '' by numpy.nan on column for google-sheet [TCTC-6530]
  tests/google_sheets/test_google_sheets.py
  toucan_connectors/google_sheets/google_sheets_connector.py
Labels: bug, Need Review

#1241 chore: bump toucan-connectors from 4.7.2 to 4.7.3
  CHANGELOG.md
  pyproject.toml
  sonar-project.properties
Labels: Need Review

#1246 fix: lts mssql install script [TCTC-6583]
  CHANGELOG.md
  toucan_connectors/install_scripts/mssql.sh
  toucan_connectors/install_scripts/mssql_TLSv1_0.sh
Labels: bug
