Repository ToucanToco/toucan-connectors, pull requests merged in 2023-02, with the labels that each got.

#939 fix(snowflake): In get_model(), only list all databases if db_name is not specified
  tests/snowflake/test_snowflake.py
  toucan_connectors/snowflake/snowflake_connector.py
Labels: bug, Need Review

#938 feat: allow empty field mysql ssl [TCTC-5306]
  CHANGELOG.md
  tests/mysql/test_mysql.py
  toucan_connectors/mysql/mysql_connector.py
Labels: Need Review

#943 feat: implemented a hubspot connector working with private apps TCTC-5345
  poetry.lock
  pyproject.toml
  tests/hubspot_private_app/__init__.py
  tests/hubspot_private_app/test_hubspot.py
  toucan_connectors/__init__.py
  toucan_connectors/hubspot_private_app/__init__.py
  toucan_connectors/hubspot_private_app/hubspot_connector.py
Labels: enhancement, Need Review

#952 [backport] feat: implemented a hubspot connector working with private apps TCTC-5345 (#943)
  poetry.lock
  pyproject.toml
  tests/hubspot_private_app/__init__.py
  tests/hubspot_private_app/test_hubspot.py
  toucan_connectors/__init__.py
  toucan_connectors/hubspot_private_app/__init__.py
  toucan_connectors/hubspot_private_app/hubspot_connector.py
Labels: enhancement, Need Review

#959 chore: v4.3.1
  CHANGELOG.md
  pyproject.toml
  sonar-project.properties
Labels: Need Review, chore
