Repository ToucanToco/toucan-connectors, pull requests merged in 2024-12, with the labels that each got.

#1843 chore: v7.4.0
  CHANGELOG.md
  pyproject.toml
  sonar-project.properties
Labels: Need Review, chore

#1844 ci: add CODEOWNERS
  .github/CODEOWNERS
Labels: Need Review, github_actions

#1848 fix(tests): wait for CI server to be ready in azure connector fixture
  tests/azure_mssql/test_azure_mssql.py
Labels: Need Review, github_actions

#1849 fix(common): prevent injection during jinja templating (v2.23)
  tests/test_common.py
  toucan_connectors/common.py
  toucan_connectors/snowflake/snowflake_connector.py
Labels: Need Review, sec, python

#1850 fix(common): prevent injection during jinja templating
  tests/test_common.py
  toucan_connectors/common.py
  toucan_connectors/snowflake/snowflake_connector.py
Labels: Need Review

#1858 fix(install scripts): use ODBC 18 for MSSQL and fix Oracle installation
  CHANGELOG.md
  tests/mssql/test_mssql.py
  tests/mssql_TLSv1_0/test_mssql_TLSv1_0.py
  toucan_connectors/azure_mssql/azure_mssql_connector.py
  toucan_connectors/install_scripts/mssql.sh
  toucan_connectors/install_scripts/mssql_TLSv1_0.sh
  toucan_connectors/install_scripts/oracle.sh
  toucan_connectors/mssql/mssql_connector.py
  toucan_connectors/mssql_TLSv1_0/mssql_connector.py
Labels: bug, Need Review
