Repository ToucanToco/toucan-connectors, pull requests merged in 2024-10, with the labels that each got.

#1784 fix(biquery): enforce int and float dtypes [TCTC-9419]
  .github/workflows/ci.yml
  CHANGELOG.md
  tests/google_big_query/test_google_big_query.py
  toucan_connectors/google_big_query/google_big_query_connector.py
Labels: bug, Need Review

#1785 chore: v7.0.3
  CHANGELOG.md
  pyproject.toml
  sonar-project.properties
Labels: Need Review

#1794 feat: add pagination configs for HTTP API Connector (TCTC-9227)
  CHANGELOG.md
  tests/http_api/test_http_api.py
  toucan_connectors/common.py
  toucan_connectors/http_api/http_api_connector.py
  toucan_connectors/http_api/http_api_data_source.py
  toucan_connectors/http_api/pagination_configs.py
  toucan_connectors/snowflake/snowflake_connector.py
  toucan_connectors/toucan_connector.py
Labels: enhancement, Need Review

#1804 chore: bump toucan-connectors to v7.1.0
  CHANGELOG.md
  pyproject.toml
  sonar-project.properties
Labels: Need Review, chore
