Repository ToucanToco/toucan-connectors, pull requests merged in 2024-06, with the labels that each got.

#1666 fix(oracle_sql): pass parameters to pandas read_sql as numeric parameters
  CHANGELOG.md
  README.md
  tests/oracle_sql/test_oracle_sql.py
  tests/test_common.py
  toucan_connectors/common.py
  toucan_connectors/oracle_sql/oracle_sql_connector.py
Labels: bug

#1668 chore: v6.2.0
  CHANGELOG.md
  pyproject.toml
  sonar-project.properties
Labels: Need Review, chore

#1669 fix: backport oracle templating variables support
  CHANGELOG.md
  README.md
  tests/oracle_sql/test_oracle_sql.py
  tests/test_common.py
  toucan_connectors/common.py
  toucan_connectors/oracle_sql/oracle_sql_connector.py
Labels: bug, Need Review

#1671 chore: v3.23.30
  CHANGELOG.md
  pyproject.toml
  sonar-project.properties
Labels: Need Review, chore

#1676 fix: do not include timezones in datetime series returned by connectors [TCTC-8804]
  CHANGELOG.md
  tests/google_sheets/test_google_sheets.py
  tests/google_sheets_2/test_google_sheets_2.py
  tests/hubspot_private_app/test_hubspot.py
  tests/one_drive/test_one_drive.py
  tests/utils/test_datetime.py
  toucan_connectors/utils/datetime.py
Labels: bug

#1677 fix: support jinja templates & fix string oracle fixtures
  tests/oracle_sql/fixtures/world.sql
  tests/oracle_sql/test_oracle_sql.py
  toucan_connectors/oracle_sql/oracle_sql_connector.py
Labels: bug, Need Review

#1681 chore: v6.3.0
  CHANGELOG.md
  pyproject.toml
  sonar-project.properties
Labels: Need Review, chore

#1689 ci: fix python 3.12 run
  .github/workflows/ci.yml
  Makefile
Labels: bug, Need Review, chore, github_actions
