Repository ToucanToco/toucan-connectors, pull requests merged in 2024-11, with the labels that each got.

#1807 fix: merge api results after their transformations (TCTC-9634)
  CHANGELOG.md
  tests/http_api/test_http_api.py
  toucan_connectors/http_api/http_api_connector.py
  toucan_connectors/http_api/pagination_configs.py
Labels: bug, Need Review

#1813 feat(mongo): when creating a df from a cursor, allow to do it by chunks (saves memory) [TCTC-9496]
  tests/mongo/test_mongo.py
  toucan_connectors/mongo/mongo_connector.py
Labels: enhancement, wip

#1820 fix(mongo): correctly type the aggreation pipeline case TCTC-9713
  toucan_connectors/mongo/mongo_connector.py
Labels: fix

#1825 fix(mongo): igore index when concatenating chunks
  CHANGELOG.md
  toucan_connectors/mongo/mongo_connector.py
Labels: bug
