Repository ToucanToco/toucan-connectors, pull requests merged in 2024-09, with the labels that each got.

#1755 feat(postgres): log exceptions rather than suppressing them
  CHANGELOG.md
  toucan_connectors/postgres/postgresql_connector.py
Labels: Need Review, refactor

#1754 chore: v6.7.0
  CHANGELOG.md
  pyproject.toml
  sonar-project.properties
Labels: Need Review, chore

#1758 refactor: make most dependencies optional
  CHANGELOG.md
  poetry.lock
  pyproject.toml
  tests/databricks/test_databricks.py
  tests/oauth2_connector/test_oauth2connector.py
  tests/test_common.py
  toucan_connectors/__init__.py
  toucan_connectors/auth.py
  toucan_connectors/awsathena/awsathena_connector.py
  toucan_connectors/azure_mssql/azure_mssql_connector.py
  toucan_connectors/clickhouse/clickhouse_connector.py
  toucan_connectors/common.py
  toucan_connectors/databricks/databricks_connector.py
  toucan_connectors/dataiku/dataiku_connector.py
  toucan_connectors/elasticsearch/elasticsearch_connector.py
  toucan_connectors/github/github_connector.py
  toucan_connectors/google_analytics/google_analytics_connector.py
  toucan_connectors/google_big_query/google_big_query_connector.py
  toucan_connectors/google_cloud_mysql/google_cloud_mysql_connector.py
  toucan_connectors/google_sheets/google_sheets_connector.py
  toucan_connectors/http_api/http_api_connector.py
  toucan_connectors/hubspot_private_app/hubspot_connector.py
  toucan_connectors/mongo/mongo_connector.py
  toucan_connectors/mssql/mssql_connector.py
  toucan_connectors/mssql_TLSv1_0/mssql_connector.py
  toucan_connectors/mysql/mysql_connector.py
  toucan_connectors/oauth2_connector/oauth2connector.py
  toucan_connectors/odata/odata_connector.py
  toucan_connectors/odbc/odbc_connector.py
  toucan_connectors/one_drive/one_drive_connector.py
  toucan_connectors/oracle_sql/oracle_sql_connector.py
  toucan_connectors/peakina/peakina_connector.py
  toucan_connectors/postgres/postgresql_connector.py
  toucan_connectors/redshift/redshift_database_connector.py
  toucan_connectors/s3/s3_connector.py
  toucan_connectors/salesforce/salesforce_connector.py
  toucan_connectors/sap_hana/sap_hana_connector.py
  toucan_connectors/snowflake/snowflake_connector.py
  toucan_connectors/snowflake_common.py
  toucan_connectors/snowflake_oauth2/snowflake_oauth2_connector.py
  toucan_connectors/soap/soap_connector.py
  toucan_connectors/toucan_connector.py
  toucan_connectors/utils/datetime.py
  toucan_connectors/utils/json_to_table.py
  toucan_connectors/utils/slugify.py
Labels: enhancement, wip, refactor

#1761 chore: v7.0.0
  CHANGELOG.md
  pyproject.toml
  sonar-project.properties
Labels: chore

#1764 fix(mysql): get_model now supports extra kwargs so it doesnt crash [TCTC-9223]
  CHANGELOG.md
  poetry.lock
  pyproject.toml
  toucan_connectors/mysql/mysql_connector.py
  toucan_connectors/redshift/redshift_database_connector.py
  toucan_connectors/snowflake_oauth2/snowflake_oauth2_connector.py
  toucan_connectors/toucan_connector.py
Labels: bug

#1769 fix: jinja templates containing parentheses or curly braces are not limited to output strings anymore
  CHANGELOG.md
  tests/test_common.py
  toucan_connectors/common.py
Labels: bug

#1770 chore: bigquery faster getmodel
  CHANGELOG.md
  toucan_connectors/google_big_query/google_big_query_connector.py
Labels: enhancement

#1771 chore: v7.0.2
  CHANGELOG.md
  pyproject.toml
  sonar-project.properties
Labels: chore

#1772 feat: when testing connection, set timeout to 10s when checking if port is opened [TCTC-7385]
  CHANGELOG.md
  toucan_connectors/toucan_connector.py
Labels: bug
