Repository ToucanToco/toucan-connectors, pull requests merged in 2024-01, with the labels that each got.

#1453 fix(lts): oracle install script
  CHANGELOG.md
  pyproject.toml
  sonar-project.properties
  toucan_connectors/install_scripts/oracle.sh
Labels: bug

#1454 fix(current): oracle install script
  CHANGELOG.md
  toucan_connectors/install_scripts/oracle.sh
Labels: bug

#1470 feat(gbq): Implement a simple status check validating the private key format
  CHANGELOG.md
  tests/conftest.py
  tests/google_big_query/test_google_big_query.py
  tests/utils/test_pem.py
  toucan_connectors/google_big_query/google_big_query_connector.py
Labels: enhancement, Need Review

#1469 fix(elasticsearch): disable verification
  CHANGELOG.md
  tests/elasticsearch/test_elasticsearch.py
  toucan_connectors/elasticsearch/elasticsearch_connector.py
Labels: bug

#1471 chore: v3.23.26
  CHANGELOG.md
  pyproject.toml
  sonar-project.properties
Labels: Need Review

#1473 [backport] feat(gbq): Implement a simple status check validating the private key format (#1470)
  CHANGELOG.md
  tests/conftest.py
  tests/google_big_query/test_google_big_query.py
  tests/utils/test_pem.py
  toucan_connectors/google_big_query/google_big_query_connector.py
Labels: Need Review

#1474 chore: v5.1.0
  CHANGELOG.md
  pyproject.toml
  sonar-project.properties
Labels: Need Review, chore

#1475 feat(google_big_query): actual connection check
  tests/google_big_query/test_google_big_query.py
  toucan_connectors/google_big_query/google_big_query_connector.py
Labels: enhancement
