Repository ToucanToco/toucan-connectors, pull requests merged in 2024-08, with the labels that each got.

#1742 feat: improve performance of DiscoverableConnector.format_db_model
  CHANGELOG.md
  toucan_connectors/toucan_connector.py
Labels: enhancement, Need Review

#1743 postgres: support `exclude_columns`
  CHANGELOG.md
  pyproject.toml
  tests/postgres/fixtures/world_postgres.sql
  tests/postgres/test_postgres.py
  tests/test_connector.py
  toucan_connectors/awsathena/awsathena_connector.py
  toucan_connectors/google_big_query/google_big_query_connector.py
  toucan_connectors/postgres/postgresql_connector.py
  toucan_connectors/postgres/utils.py
  toucan_connectors/snowflake/snowflake_connector.py
  toucan_connectors/toucan_connector.py
Labels: enhancement, Need Review, :skull: DO NOT MERGE ! :skull:

#1746 chore: v6.6.0
  CHANGELOG.md
  pyproject.toml
  sonar-project.properties
Labels: Need Review

#1751 feat: add token_header_name option to http connectors (TCTC-8945)
  CHANGELOG.md
  tests/test_auth.py
  toucan_connectors/auth.py
Labels: enhancement, Need Review, python
