Repository ToucanToco/toucan-connectors, pull requests merged in 2024-07, with the labels that each got.

#1697 fix(auth): allow auth to be instanciated without any positional parameters [TCTC-8954]
  .pre-commit-config.yaml
  CHANGELOG.md
  poetry.lock
  pyproject.toml
  tests/http_api/test_http_api.py
  tests/test_auth.py
  toucan_connectors/auth.py
  toucan_connectors/hubspot_private_app/hubspot_connector.py
Labels: bug, Need Review

#1698 fix(bigquery): make get_status work with JWT auth [TCTC-8923]
  CHANGELOG.md
  pyproject.toml
  tests/google_big_query/test_google_big_query.py
  toucan_connectors/google_big_query/google_big_query_connector.py
Labels: bug, Need Review

#1699 chore: v6.3.1
  CHANGELOG.md
  pyproject.toml
  sonar-project.properties
Labels: Need Review, chore

#1711 fix(athena): correct interpolation for parameters [TCTC-9024]
  .github/workflows/ci.yml
  CHANGELOG.md
  pyproject.toml
  tests/awsathena/test_athena_integration.py
  tests/awsathena/test_awsathena.py
  toucan_connectors/awsathena/awsathena_connector.py
Labels: bug, enhancement, Need Review

#1712 feat(hubspot): allow to query specific properties [TCTC-9025]
  CHANGELOG.md
  tests/hubspot_private_app/test_hubspot.py
  toucan_connectors/hubspot_private_app/hubspot_connector.py
Labels: enhancement

#1714 feat(hubspot): allow to list and select custom datasets [TCTC-9025]
  CHANGELOG.md
  tests/hubspot_private_app/test_hubspot.py
  toucan_connectors/hubspot_private_app/hubspot_connector.py
Labels: enhancement
