Repository ToucanToco/toucan-connectors, pull requests merged in 2024-03, with the labels that each got.

#1548 feat(dependabot): group dependency bumps
  .github/dependabot.yml
Labels: enhancement, Need Review, dependencies

#1552 fix(gbq): do not ignore partitioning columns when listing table structure [TCTC-7946]
  CHANGELOG.md
  tests/google_big_query/test_google_big_query.py
  toucan_connectors/google_big_query/google_big_query_connector.py
Labels: bug

#1556 fix(deps): tune dependabot updates
  .github/dependabot.yml
Labels: bug, Need Review, dependencies, github_actions

#1567 chore: v6.0.0
  CHANGELOG.md
  pyproject.toml
  sonar-project.properties
Labels: Need Review, chore

#1568 refactor(deps): drop toucan_data_sdk dependency
  Makefile
  poetry.lock
  pyproject.toml
  tests/utils/test_json_to_table.py
  toucan_connectors/common.py
  toucan_connectors/http_api/http_api_connector.py
  toucan_connectors/soap/soap_connector.py
  toucan_connectors/utils/json_to_table.py
  toucan_connectors/utils/slugify.py
Labels: enhancement, dependencies

#1571 chore: remove bearer dependencyu
  poetry.lock
  pyproject.toml
  toucan_connectors/toucan_connector.py
Labels: chore, dependencies

#1574 fix(dependabot): adapt ignore conditions
  .github/dependabot.yml
Labels: bug, Need Review, dependencies

#1570 fix: restore the HubspotPrivateApp connector
  CHANGELOG.md
  poetry.lock
  pyproject.toml
  tests/hubspot_private_app/__init__.py
  tests/hubspot_private_app/test_hubspot.py
  toucan_connectors/__init__.py
  toucan_connectors/hubspot_private_app/__init__.py
  toucan_connectors/hubspot_private_app/hubspot.png
  toucan_connectors/hubspot_private_app/hubspot_connector.py
Labels: bug, Need Review

#1579 chore: v6.1.0
  CHANGELOG.md
  pyproject.toml
  sonar-project.properties
Labels: Need Review, chore

#1580 fix: elasticsearch form schema [TCTC-8032]
  CHANGELOG.md
  pyproject.toml
  sonar-project.properties
  toucan_connectors/elasticsearch/elasticsearch_connector.py
Labels: bug
