Repository ToucanToco/toucan-connectors, pull requests merged in 2025-07, with the labels that each got.

#2003 feat(postgres): bump psycopg to v3 & use sqlalchemy (TCTC-11016)
  CHANGELOG.md
  pyproject.toml
  tests/odbc/test_odbc.py
  tests/postgres/test_postgres.py
  toucan_connectors/common.py
  toucan_connectors/postgres/postgresql_connector.py
  uv.lock
Labels: enhancement, Need Review, dependencies

#2010 fix(http_api): reindex DataFrame in _retrieve_data [TCTC-11181]
  CHANGELOG.md
  tests/http_api/test_http_api.py
  toucan_connectors/http_api/http_api_connector.py
Labels: bug, Need Review

#2018 chore: v9.2.0
  CHANGELOG.md
  pyproject.toml
  uv.lock
Labels: Need Review
