Repository ToucanToco/toucan-connectors, pull requests merged in 2025-02, with the labels that each got.

#1894 fix: can instantiate connectors without callbacks/secrets-keeper (TCTC-10081)
  CHANGELOG.md
  tests/google_sheets/test_google_sheets.py
  tests/oauth2_connector/test_oauth2connector.py
  toucan_connectors/google_sheets/google_sheets_connector.py
  toucan_connectors/oauth2_connector/oauth2connector.py
Labels: bug, Need Review

#1896 fix: ignore retrieve_token property in google sheets schema
  CHANGELOG.md
  tests/google_sheets/test_google_sheets.py
  toucan_connectors/google_sheets/google_sheets_connector.py
Labels: bug, Need Review

#1897 chore: v7.7.5
  CHANGELOG.md
  pyproject.toml
  sonar-project.properties
  uv.lock
Labels: Need Review, chore

#1898 fix: can instantiate oauth2 connectors without oauth backend fields (TCTC-10138)
  CHANGELOG.md
  tests/conftest.py
  tests/github/test_github.py
  tests/oauth2_connector/test_oauth2connector.py
  tests/one_drive/test_one_drive.py
  tests/salesforce/test_salesforce.py
  tests/snowflake_oauth2/test_snowflake_oauth2.py
  toucan_connectors/github/github_connector.py
  toucan_connectors/oauth2_connector/oauth2connector.py
  toucan_connectors/one_drive/one_drive_connector.py
  toucan_connectors/salesforce/salesforce_connector.py
  toucan_connectors/snowflake_oauth2/snowflake_oauth2_connector.py
Labels: bug, Need Review, python

#1899 chore: v7.7.6
  CHANGELOG.md
  pyproject.toml
  sonar-project.properties
  uv.lock
Labels: Need Review, chore

#1901 chore: bump actions/cache action
  .github/workflows/ci.yml
Labels: chore

#1900 fix: can generate the connector unique identifier (TCTC-10081)
  CHANGELOG.md
  tests/google_sheets/test_google_sheets.py
  toucan_connectors/google_sheets/google_sheets_connector.py
Labels: bug, Need Review

#1902 chore: v7.7.7
  CHANGELOG.md
  pyproject.toml
  sonar-project.properties
  uv.lock
Labels: Need Review, chore

#1904 fix(utils/datetime): coerce pd.to_datetime errors
  CHANGELOG.md
  tests/utils/test_datetime.py
  toucan_connectors/utils/datetime.py
Labels: bug, Need Review

#1905 chore: v7.7.8
  CHANGELOG.md
  pyproject.toml
  sonar-project.properties
  uv.lock
Labels: Need Review
