Repository ToucanToco/toucan-connectors, pull requests merged in 2025-01, with the labels that each got.

#1868 fix(ci): pin poetry>=1.8,<1.9
  .github/workflows/ci.yml
  .github/workflows/publish.yml
Labels: bug, github_actions

#1818 feat: support python 3.13
  .github/workflows/ci.yml
  poetry.lock
  pyproject.toml
Labels: enhancement, Need Review

#1879 chore: v7.6.0
  CHANGELOG.md
  pyproject.toml
  sonar-project.properties
Labels: Need Review

#1881 fix: check files format in lint check
  Makefile
  tests/conftest.py
  tests/http_api/test_http_api.py
  tests/mssql/test_mssql.py
  tests/mssql_TLSv1_0/test_mssql_TLSv1_0.py
  tests/oauth2_connector/test_oauth2connector.py
  tests/oracle_sql/test_oracle_sql.py
  tests/snowflake_oauth2/test_snowflake_oauth2.py
  tests/test_common.py
  tests/test_google_credentials.py
  tests/test_sql_query_helper.py
  toucan_connectors/auth.py
  toucan_connectors/clickhouse/clickhouse_connector.py
  toucan_connectors/common.py
  toucan_connectors/github/helpers.py
  toucan_connectors/google_credentials.py
  toucan_connectors/google_sheets/google_sheets_connector.py
  toucan_connectors/http_api/http_api_connector.py
  toucan_connectors/http_api/http_api_data_source.py
  toucan_connectors/mongo/mongo_connector.py
  toucan_connectors/mssql/mssql_connector.py
  toucan_connectors/mssql_TLSv1_0/mssql_connector.py
  toucan_connectors/mysql/mysql_connector.py
  toucan_connectors/one_drive/one_drive_connector.py
  toucan_connectors/oracle_sql/oracle_sql_connector.py
  toucan_connectors/postgres/postgresql_connector.py
  toucan_connectors/salesforce/salesforce_connector.py
  toucan_connectors/soap/soap_connector.py
Labels: Need Review, fix

#1883 feat: switch from poetry to uv
  .github/dependabot.yml
  .github/workflows/ci.yml
  .github/workflows/publish.yml
  .pre-commit-config.yaml
  CHANGELOG.md
  Makefile
  README.md
  poetry.lock
  pyproject.toml
  tests/awsathena/test_awsathena.py
  tests/mongo/test_mongo.py
  tests/redshift/test_redshift.py
  tests/test_connection_manager.py
  tests/test_query_manager.py
  tests/utils/test_datetime.py
  toucan_connectors/awsathena/awsathena_connector.py
  toucan_connectors/common.py
  toucan_connectors/condition_translator.py
  toucan_connectors/connection_manager.py
  toucan_connectors/databricks/databricks_connector.py
  toucan_connectors/elasticsearch/elasticsearch_connector.py
  toucan_connectors/github/github_connector.py
  toucan_connectors/google_analytics/google_analytics_connector.py
  toucan_connectors/google_big_query/google_big_query_connector.py
  toucan_connectors/google_sheets/google_sheets_connector.py
  toucan_connectors/mongo/mongo_connector.py
  toucan_connectors/mysql/mysql_connector.py
  toucan_connectors/oauth2_connector/oauth2connector.py
  toucan_connectors/one_drive/one_drive_connector.py
  toucan_connectors/pandas_translator.py
  toucan_connectors/postgres/postgresql_connector.py
  toucan_connectors/query_manager.py
  toucan_connectors/salesforce/salesforce_connector.py
  toucan_connectors/snowflake_common.py
  toucan_connectors/snowflake_oauth2/snowflake_oauth2_connector.py
  toucan_connectors/sql_query_helper.py
  toucan_connectors/toucan_connector.py
  toucan_connectors/utils/json_to_table.py
  uv.lock
Labels: enhancement, Need Review, tech

#1886 fix: include non-code data in uv package
  pyproject.toml
Labels: bug, Need Review

#1885 fix(google_credentials): fix imports [TCTC-9873]
  CHANGELOG.md
  toucan_connectors/google_credentials.py
Labels: bug, Need Review

#1842 feat: add authentication configs (TCTC-9914)
  pyproject.toml
  tests/http_api/test_authentication_configs.py
  tests/http_api/test_http_api.py
  toucan_connectors/http_api/authentication_configs.py
  toucan_connectors/http_api/http_api_connector.py
  toucan_connectors/http_api/pagination_configs.py
  toucan_connectors/json_wrapper.py
  toucan_connectors/oauth2_connector/oauth2connector.py
  uv.lock
Labels: enhancement, Need Review, python

#1887 chore: v7.7.0
  CHANGELOG.md
  pyproject.toml
  sonar-project.properties
Labels: Need Review, chore

#1891 feat: accept null refresh-token on oauth-tokens
  CHANGELOG.md
  tests/http_api/test_authentication_configs.py
  toucan_connectors/http_api/authentication_configs.py
  uv.lock
Labels: enhancement, Need Review

#1892 chore: v7.7.3
  CHANGELOG.md
  pyproject.toml
  sonar-project.properties
  uv.lock
Labels: Need Review, chore
