Repository ToucanToco/toucan-connectors, pull requests merged in 2025-04, with the labels that each got.

#1943 feat!(mssql): allow custom certificates and use sql alchemy instead [TCTC-10323]
  CHANGELOG.md
  pyproject.toml
  tests/conftest.py
  tests/docker-compose.yml
  tests/mssql/conf/mssql2022.conf
  tests/mssql/conf/mssql2022.dummy.key
  tests/mssql/conf/mssql2022.dummy.pem
  tests/mssql/test_mssql.py
  tests/mysql/test_mysql.py
  tests/test_common.py
  toucan_connectors/azure_mssql/azure_mssql_connector.py
  toucan_connectors/common.py
  toucan_connectors/mssql/mssql_connector.py
  toucan_connectors/mysql/mysql_connector.py
Labels: enhancement, wip

#1962 chore: v8.0.0
  CHANGELOG.md
  pyproject.toml
  uv.lock
Labels: Need Review

#1964 fix(azure): export CONNECTOR_OK
  CHANGELOG.md
  toucan_connectors/azure_mssql/azure_mssql_connector.py
Labels: bug, Need Review

#1969 fix(mssql): only wait 5 seconds for the database and table list in connector form
  CHANGELOG.md
  toucan_connectors/mssql/mssql_connector.py
Labels: bug, Need Review

#1971 fix(mssql): actually use overriden timeout value
  CHANGELOG.md
  toucan_connectors/azure_mssql/azure_mssql_connector.py
  toucan_connectors/common.py
  toucan_connectors/mssql/mssql_connector.py
Labels: Need Review, fix

#1972 chore: v8.0.2
  CHANGELOG.md
  pyproject.toml
  uv.lock
Labels: Need Review, chore
